### ISSUE TITLE
Catkin make error

### ISSUE THREAD

**Issue by NamTruongTran0** [maprdhm/SPACiSS#1]
Hey,

thank you for your awesome work.
Unfortunately i getting this error message after catkin_make:

```
CMake Error at /home/nartmangnourt/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/FindQt4.cmake:1314 (message):
  Found unsuitable Qt version "5.12.8" from /usr/bin/qmake, this code
  requires Qt 4.x
Call Stack (most recent call first):
  Spaciss/pedsim_simulator/CMakeLists.txt:24 (find_package)


-- Configuring incomplete, errors occurred!
make: *** [Makefile:324: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
```

Thank you in advance for your help :)

**Comment by maprdhm** [comment]
Hi,

Thank you for your interest.

The message mentions that you have Qt version 5.12.8 installed while the code requires Qt version 4.
Either try to install SPACiSS using the noetic branch (which works with Qt 5), or install Qt version 4 if you want to use the master branch.
